set expandtab
set tabstop=2

set nocp

syntax on

set ignorecase
set smartcase

set incsearch

set scrolloff=2

set wildmode=longest,list

filetype plugin on

nmap <F5> :make <CR>
nmap <C-F5> :!make clean; make <CR>
